project/desa/urls.py
from django.urls import path, re_path

from .views import DesaListView, DesaFormView, DesaDeleteView

urlpatterns = [
    path('', DesaListView.as_view(), name="index"),
    path('tambah', DesaFormView.as_view(), name="tambah"),
    re_path(r'^ubah/(?P<ubah_id>[0-9]+)/$', DesaFormView.as_view(mode='ubah'), name="ubah"),
    re_path(r'^hapus/(?P<hapus_id>[0-9]+)/$', DesaDeleteView.as_view(), name="hapus"),
]

project/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import DashboardListView

urlpatterns = [
    path('', DashboardListView.as_view(), name="index"),
    path('desa/', include(('desa.urls', 'desa'), namespace="desa")),
    path('grup/', include(('grup.urls', 'grup'), namespace="grup")),
    path('kontak/', include(('kontak.urls', 'kontak'), namespace="kontak")),
    path('pesan/', include(('pesan.urls', 'pesan'), namespace="pesan")),
    path('admin/', admin.site.urls),
]

project/pesan/urls.py
from django.urls import path, re_path

from .views import PesanMassalListView, TemplateListView, TemplateFormView, TemplateDeleteView, sendMessageMany

urlpatterns = [
    path('', PesanMassalListView.as_view(), name="index"),
    path('templates/', TemplateListView.as_view(), name="templates"),
    path('templates/tambah/', TemplateFormView.as_view(), name="templates-tambah"),
    path('kirim/massal/', sendMessageMany, name="kirim-massal"),
    re_path(r'^templates/ubah/(?P<ubah_id>[0-9]+)/$', TemplateFormView.as_view(mode='ubah'), name="templates-ubah"),
    re_path(r'^templates/hapus/(?P<hapus_id>[0-9]+)/$', TemplateDeleteView.as_view(), name="templates-hapus"),
]

project/pesan/models.py
from django.db import models

from grup.models import Grup
from .enums import IsEnum, ContentType

# Create your models here.

class Templates(models.Model):
    group   = models.ForeignKey(Grup, on_delete=models.SET_NULL, null=True)
    name    = models.CharField(max_length=50)
    text    = models.TextField()

    def __str__(self):
        return "{}".format(self.name)
    
    class Meta:
        db_table    = "templates"


class Outbox(models.Model):
    machine_id      = models.IntegerField(null=True, default=1)
    is_group        = models.CharField(
        max_length  = 3,
        choices     = [(tag, tag.value) for tag in IsEnum],
        null        = True,
        default     = 'N'
    )
    group_name      = models.CharField(max_length=100, null=True)
    desa_name       = models.CharField(max_length=50, null=True)
    grup_name       = models.CharField(max_length=50, null=True)
    contact         = models.CharField(max_length=50, null=True)
    is_reply        = models.CharField(
        max_length  = 3,
        choices     = [(tag, tag.value) for tag in IsEnum],
        null        = True,
        default     = 'N'
    )
    content_type    = models.CharField(
        max_length  = 10,
        choices     = [(tag, tag.value) for tag in IsEnum],
        null        = True,
        default     = 'Text'
    )
    content_location= models.TextField(null=True)
    title_message   = models.CharField(max_length=50, null=True)
    message         = models.TextField(null=True)
    sent_at         = models.DateTimeField(null=True)
    processed       = models.CharField(
        max_length  = 3,
        choices     = [(tag, tag.value) for tag in IsEnum],
        null        = True,
        default     = 'N'
    )
    processed_at    = models.DateTimeField(null=True)
    created_at      = models.DateTimeField(null=True, auto_now_add=True)
    updated_at      = models.DateTimeField(null=True, auto_now_add=True)
    contact_parser  = models.CharField(max_length=50, null=True)

    def __str__(self):
        return "{}".format(self.id)
    
    class Meta:
        db_table    = "outbox"

project/pesan/forms.py
from django import forms

from .models import Templates
from grup.models import Grup
from desa.models import Desa

class TemplateForm(forms.ModelForm):
    class Meta:
        model   = Templates
        fields  = ['group', 'name', 'text']
        labels  = {
            'group': 'Grup',
            'name': 'Nama Template',
            'text': 'Isi Template',
        }
        widgets = {
            'group': forms.Select(
                attrs   = {
                    'class': 'form-control',
                }
            ),
            'name': forms.TextInput(
                attrs   = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan Nama Template',
                }
            ),
            'text': forms.Textarea(
                attrs   = {
                    'class': 'form-control',
                }
            )
        }


class SendForm(forms.Form):
    group   = forms.ModelChoiceField(
        queryset    = Grup.objects.all(),
        widget      = forms.Select(
            attrs       = {
                'class': 'form-control'
            }
        )
    )
    desa    = forms.ModelChoiceField(
        queryset    = Desa.objects.all(),
        widget      = forms.Select(
            attrs   = {
                'class': 'form-control'
            }
        ),
        required=False
    )
    template_pesan  = forms.ModelChoiceField(
        queryset    = Templates.objects.all(),
        widget      = forms.Select(
            attrs   = {
                'class': 'form-control'
            }
        )
    )

project/pesan/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView, View, RedirectView

# Create your views here.
from .models import Templates, Outbox
from kontak.models import Contacts
from grup.models import Grup
from desa.models import Desa
from .forms import TemplateForm, SendForm


class TemplateListView(TemplateView):
    template_name   = 'pesan/templates.html'

    def get_context_data(self, *args, **kwargs):
        templates   = reversed(Templates.objects.all().order_by('id'))
        context     = {
            'Judul': 'Lihat Templates',
            'Judul_Tabel': 'Tabel Templates',
            'Templates': templates,
        }
        return context


class TemplateFormView(View):
    template_name   = 'pesan/templates-tambah.html'
    form    = TemplateForm()
    mode    = None
    context = {}

    def get(self, *args, **kwargs):
        if self.mode == 'ubah':
            template_ubah   = Templates.objects.get(id=kwargs['ubah_id'])
            data            = template_ubah.__dict__
            self.form       = TemplateForm(initial=data, instance=template_ubah)
        self.context    = {
            'Judul' : 'Tambah Templates',
            'Subjudul'  : 'Masukkan Template Baru',
            'templates_form'    : self.form
        }
        return render(self.request, self.template_name, self.context)
    
    def post(self, *args, **kwargs):
        if kwargs.__contains__('ubah_id'):
            template_ubah   = Templates.objects.get(id=kwargs['ubah_id'])
            self.form       = TemplateForm(self.request.POST, instance=template_ubah)
        else:
            self.form   = TemplateForm(self.request.POST)
        if self.form.is_valid():
            self.form.save()
        return redirect('pesan:templates')


class TemplateDeleteView(RedirectView):
    pattern_name    = 'pesan:templates'
    permanent       = False
    query_string    = False

    def get_redirect_url(self, *args, **kwargs):
        hapus_id    = kwargs['hapus_id']
        Templates.objects.filter(id=hapus_id).delete()
        return super().get_redirect_url()


class PesanMassalListView(TemplateView):
    template_name   = 'pesan/index.html'

    def get_context_data(self, *args, **kwargs):
        # get name of template
        name_template   = Templates.objects.all().values('name').distinct()
        
        # count sent_at based on name_template
        list_template   = []
        for name in name_template:
            name            = name.get('name')
            count_outbox    = Outbox.objects.filter(title_message=name).filter(created_at__isnull=False).filter(sent_at__isnull=False).count()
            each_list       = [name, count_outbox]
            list_template.append(each_list)
        context     = {
            'Judul': 'Lihat Pengiriman Pesan Massal',
            'Judul_Tabel': 'Tabel Pengiriman Pesan Massal',
            'list_template': list_template,
        }
        return context


def sendMessageMany(request):
    send_form   = SendForm(request.POST or None)
    error       = None
    if request.method == 'POST':
        if send_form.is_valid():
            # get data from SendForm
            group           = send_form.cleaned_data.get('group')
            desa            = send_form.cleaned_data.get('desa')
            name_template   = send_form.cleaned_data.get('template_pesan')

            # get id for each 'grup' and 'desa'
            group_id    = Grup.objects.get(name=group).id
            if desa is not None:
                desa_id     = Desa.objects.get(name=desa).id

            # get message from name template
            template_pesan  = Templates.objects.get(name=name_template).text
            
            # get contact from Contacts
            store = None
            list_outbox = []
            if desa is not None:
                get_contacts= Contacts.objects.filter(group_id=group_id).filter(desa_id=desa_id).values('contact')
                for no_kontak in get_contacts:
                    store = Outbox(contact=no_kontak.get('contact'), message=template_pesan, grup_name=group, desa_name=desa, title_message=name_template)
                    list_outbox.append(store)
            else:
                get_contacts= Contacts.objects.filter(group_id=group_id).values('contact')
                for no_kontak in get_contacts:
                    store = Outbox(contact=no_kontak.get('contact'), message=template_pesan, grup_name=group, title_message=name_template)
                    list_outbox.append(store)
            
            # save to Outbox
            Outbox.objects.bulk_create(list_outbox)

            return redirect('pesan:index')
        else:
            error = send_form.errors
    context = {
        'Judul'     : 'Kirim Pesan Massal',
        'Subjudul'  : 'Mengirim Pesan Massal',
        'send_form' : send_form,
        'error'     : error
    }
    return render(request, 'pesan/kirim-massal.html', context)

project/pesan/templates/pesan/index.html
{% extends 'base.html' %}
{% load static %}


{% block styles_custom %}
<!-- Custom styles for this page -->
<link href="{% static "vendor/datatables/dataTables.bootstrap4.min.css" %}" rel="stylesheet">
{% endblock styles_custom %}


{% block heading %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{Judul}}</h1>
    <a href="{% url "pesan:kirim-massal" %}" class="btn btn-success btn-icon-split">
        <span class="icon text-white-50">
            <i class="fas fa-plus"></i>
        </span>
        <span class="text">Kirim Pesan Massal</span>
    </a>
</div>
{% endblock heading %}


{% block data_table %}
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">{{Judul_Tabel}}</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Judul Pesan</th>
                    <th>Pesan Terkirim</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>No</th>
                    <th>Judul Pesan</th>
                    <th>Pesan Terkirim</th>
                </tr>
            </tfoot>
            <tbody>
                {% for data in list_template %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{data.0}}</td>
                    <td>{{data.1}} pesan</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>
{% endblock data_table %}


{% block scripts_custom %}
<!-- Page level plugins -->
<script src="{% static "vendor/datatables/jquery.dataTables.min.js" %}"></script>
<script src="{% static "vendor/datatables/dataTables.bootstrap4.min.js" %}"></script>

<!-- Page level custom scripts -->
<script src="{% static "js/demo/datatables-demo.js" %}"></script>
{% endblock scripts_custom %}

project/pesan/templates/pesan/kirim-massal.html
{% extends 'base.html' %}

{% block heading %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{Judul}}</h1>
</div>
{% endblock heading %}

{% block tambah %}
<div class="row">
    <div class="col-lg-12">
        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{Subjudul}}</h6>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in send_form %}
                        <div class="form-group row">
                            <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{field.label}}</label>
                            <div class="col-sm-10">
                                {{field}}
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary float-right">Kirim</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock tambah %}

project/pesan/templates/pesan/templates-tambah.html
{% extends 'base.html' %}
{% load static %}

{% block heading %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{Judul}}</h1>
</div>
{% endblock heading %}


{% block tambah %}
<div class="row">
    <div class="col-lg-12">
        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{Subjudul}}</h6>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in templates_form %}
                        <div class="form-group row">
                            <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{field.label}}</label>
                            <div class="col-sm-10">
                                {{field}}
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-success float-right">Buat</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock tambah %}

project/pesan/templates/pesan/templates.html
{% extends 'base.html' %}
{% load static %}

{% block styles_custom %}
<!-- Custom styles for this page -->
<link href="{% static "vendor/datatables/dataTables.bootstrap4.min.css" %}" rel="stylesheet">
{% endblock styles_custom %}

{% block heading %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{Judul}}</h1>
    <a href="{% url "pesan:templates-tambah" %}" class="btn btn-success btn-icon-split">
        <span class="icon text-white-50">
            <i class="fas fa-plus"></i>
        </span>
        <span class="text">Tambah Templates</span>
    </a>
</div>
{% endblock heading %}

{% block data_table %}
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">{{Judul_Tabel}}</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama Template</th>
                    <th>Isi Template</th>
                    <th>Grup</th>
                    <th>Menu</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>No</th>
                    <th>Nama Template</th>
                    <th>Isi Template</th>
                    <th>Grup</th>
                    <th>Menu</th>
                </tr>
            </tfoot>
            <tbody>
                {% for template in Templates %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{template.name}}</td>
                    <td>{{template.text}}</td>
                    <td>{{template.group}}</td>
                    <td>
                        <a class="btn btn-warning" href="{% url 'pesan:templates-ubah' template.id %}"><i class="fas fa-edit"></i></a>
                        <a class="btn btn-danger" href="{% url 'pesan:templates-hapus' template.id %}"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>
{% endblock data_table %}


{% block scripts_custom %}
<!-- Page level plugins -->
<script src="{% static "vendor/datatables/jquery.dataTables.min.js" %}"></script>
<script src="{% static "vendor/datatables/dataTables.bootstrap4.min.js" %}"></script>

<!-- Page level custom scripts -->
<script src="{% static "js/demo/datatables-demo.js" %}"></script>
{% endblock scripts_custom %}