project/desa/urls.py
from django.urls import path, re_path

from .views import DesaListView, DesaFormView, DesaDeleteView

urlpatterns = [
    path('', DesaListView.as_view(), name="index"),
    path('tambah', DesaFormView.as_view(), name="tambah"),
    re_path(r'^ubah/(?P<ubah_id>[0-9]+)/$', DesaFormView.as_view(mode='ubah'), name="ubah"),
    re_path(r'^hapus/(?P<hapus_id>[0-9]+)/$', DesaDeleteView.as_view(), name="hapus"),
]

project/kontak/urls.py
from django.urls import path, re_path

from .views import KontakListView, KontakCariListView, KontakFormView, KontakDeleteView

urlpatterns = [
    path('', KontakListView.as_view(), name="index"),
    path('cari/', KontakCariListView.as_view(), name="cari"),
    path('tambah/', KontakFormView.as_view(), name="tambah"),
    re_path(r'^ubah/(?P<ubah_id>[0-9]+)/$', KontakFormView.as_view(mode='ubah'), name="ubah"),
    re_path(r'^hapus/(?P<hapus_id>[0-9]+)/$', KontakDeleteView.as_view(), name="hapus"),
]

project/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import DashboardListView

urlpatterns = [
    path('', DashboardListView.as_view(), name="index"),
    path('desa/', include(('desa.urls', 'desa'), namespace="desa")),
    path('grup/', include(('grup.urls', 'grup'), namespace="grup")),
    path('kontak/', include(('kontak.urls', 'kontak'), namespace="kontak")),
    path('pesan/', include(('pesan.urls', 'pesan'), namespace="pesan")),
    path('admin/', admin.site.urls),
]

project/pesan/urls.py
from django.urls import path, re_path

from .views import PesanMassalListView, TemplateListView, TemplateFormView, TemplateDeleteView, sendMessageMany

urlpatterns = [
    path('', PesanMassalListView.as_view(), name="index"),
    path('templates/', TemplateListView.as_view(), name="templates"),
    path('templates/tambah/', TemplateFormView.as_view(), name="templates-tambah"),
    path('kirim/massal/', sendMessageMany, name="kirim-massal"),
    re_path(r'^templates/ubah/(?P<ubah_id>[0-9]+)/$', TemplateFormView.as_view(mode='ubah'), name="templates-ubah"),
    re_path(r'^templates/hapus/(?P<hapus_id>[0-9]+)/$', TemplateDeleteView.as_view(), name="templates-hapus"),
]

project/templates/snippets/scripts.html
{% load static %}

<!-- Bootstrap core JavaScript-->
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static "js/sb-admin-2.min.js" %}"></script>

project/templates/snippets/sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url "index" %}">
        <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Broadcast <sup>WhatsApp</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url "index" %}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Menu Utama
    </div>

    <!-- Nav Item - Kontak Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseKontak" aria-expanded="true" aria-controls="collapseKontak">
            <i class="fas fa-fw fa-phone"></i>
            <span>Kontak</span>
        </a>
        <div id="collapseKontak" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Menu:</h6>
                <a class="collapse-item" href="{% url "kontak:index" %}"><i class="fas fa-fw fa-address-book"></i><span> Lihat Kontak</span></a>
                <a class="collapse-item" href="{% url "kontak:tambah" %}"><i class="fas fa-fw fa-plus"></i><span> Tambah Kontak</span></a>
                <a class="collapse-item" href="{% url "kontak:cari" %}"><i class="fas fa-fw fa-search"></i><span> Cari Kontak</span></a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Pesan Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePesan" aria-expanded="true" aria-controls="collapsePesan">
            <i class="fas fa-fw fa-inbox"></i>
            <span>Pesan</span>
            </a>
        <div id="collapsePesan" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Menu:</h6>
                <a class="collapse-item" href="{% url "pesan:index" %}"><i class="fas fa-fw fa-paper-plane"></i><span> Pesan Massal</span></a>
                <a class="collapse-item" href="{% url "pesan:templates" %}"><i class="fas fa-fw fa-archive"></i><span> Template</span></a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Lainnya
    </div>

    <!-- Nav Item - Grup Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseGrup" aria-expanded="true" aria-controls="collapseGrup">
            <i class="fas fa-fw fa-user-circle"></i>
            <span>Grup</span>
        </a>
        <div id="collapseGrup" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Menu:</h6>
                <a class="collapse-item" href="{% url "grup:index" %}"><i class="fas fa-fw fa-users"></i><span> Lihat Grup</span></a>
                <a class="collapse-item" href="{% url "grup:tambah" %}"><i class="fas fa-fw fa-user-plus"></i><span> Tambah Grup</span></a>
            </div>
        </div>
    </li>
    
    <!-- Nav Item - Desa Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseDesa" aria-expanded="true" aria-controls="collapseKategori">
            <i class="fas fa-fw fa-flag"></i>
            <span>Desa</span>
        </a>
        <div id="collapseDesa" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Menu:</h6>
                <a class="collapse-item" href="{% url "desa:index" %}"><i class="fas fa-fw fa-map"></i><span> Lihat Desa</span></a>
                <a class="collapse-item" href="{% url "desa:tambah" %}"><i class="fas fa-fw fa-street-view"></i><span> Tambah Desa</span></a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="{% url "index" %}">
        <i class="fas fa-fw fa-info-circle"></i>
        <span>Informasi</span></a>
    </li>


    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
  <!-- End of Sidebar -->

project/templates/snippets/styles.html
{% load static %}

<!-- Custom fonts for this template-->
<link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{% static "css/sb-admin-2.min.css" %}" rel="stylesheet">