project/desa/urls.py
from django.urls import path, re_path

from .views import DesaListView, DesaFormView, DesaDeleteView

urlpatterns = [
    path('', DesaListView.as_view(), name="index"),
    path('tambah', DesaFormView.as_view(), name="tambah"),
    re_path(r'^ubah/(?P<ubah_id>[0-9]+)/$', DesaFormView.as_view(mode='ubah'), name="ubah"),
    re_path(r'^hapus/(?P<hapus_id>[0-9]+)/$', DesaDeleteView.as_view(), name="hapus"),
]

project/grup/urls.py
from django.urls import path, re_path

from .views import GrupListView, GrupFormView, GrupDeleteView

urlpatterns = [
    path('', GrupListView.as_view(), name="index"),
    path('tambah/', GrupFormView.as_view(), name="tambah"),
    re_path(r'^ubah/(?P<ubah_id>[0-9]+)/$', GrupFormView.as_view(mode='ubah'), name="ubah"),
    re_path(r'^hapus/(?P<hapus_id>[0-9]+)/$', GrupDeleteView.as_view(), name="hapus"),
]

project/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import DashboardListView

urlpatterns = [
    path('', DashboardListView.as_view(), name="index"),
    path('desa/', include(('desa.urls', 'desa'), namespace="desa")),
    path('grup/', include(('grup.urls', 'grup'), namespace="grup")),
    path('kontak/', include(('kontak.urls', 'kontak'), namespace="kontak")),
    path('pesan/', include(('pesan.urls', 'pesan'), namespace="pesan")),
    path('admin/', admin.site.urls),
]

project/grup/models.py
from django.db import models

# Create your models here.
class Grup(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return "{}".format(self.name)
    
    class Meta:
        db_table    = "group"

project/grup/forms.py
from django import forms

from .models import Grup

class GrupForm(forms.ModelForm):
    class Meta:
        model   = Grup
        fields  = ['name']
        widgets = {
            'name': forms.TextInput(
                attrs   = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan nama grup',
                }
            )
        }

project/grup/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView, View, RedirectView

# Create your views here.
from .models import Grup
from .forms import GrupForm


class GrupListView(TemplateView):
    template_name   = 'grup/index.html'
    
    def get_context_data(self, *args, **kwargs):
        grups = reversed(Grup.objects.all().order_by('id'))
        context = {
            'Judul': 'Lihat Grup',
            'Judul_Tabel': 'Tabel Grup',
            'Grups': grups,
        }
        return context


class GrupFormView(View):
    template_name   = 'grup/tambah.html'
    form    = GrupForm()
    mode    = None
    context = {}

    def get(self, *args, **kwargs):
        if self.mode == 'ubah':
            grup_ubah   = Grup.objects.get(id=kwargs['ubah_id'])
            data        = grup_ubah.__dict__
            self.form   = GrupForm(initial=data, instance=grup_ubah)
        self.context = {
            'Judul'     : 'Tambah Grup',
            'Subjudul'  : 'Masukkan Grup Baru',
            'grup_form' : self.form,
        }
        return render(self.request, self.template_name, self.context)

    def post(self, *args, **kwargs):
        if kwargs.__contains__('ubah_id'):
            grup_ubah   = Grup.objects.get(id=kwargs['ubah_id'])
            self.form   = GrupForm(self.request.POST, instance=grup_ubah)
        else:
            self.form   = GrupForm(self.request.POST)
        if self.form.is_valid():
            self.form.save()
        return redirect('grup:index')


class GrupDeleteView(RedirectView):
    pattern_name    = 'grup:index'
    permanent       = False
    query_string    = False

    def get_redirect_url(self, *args, **kwargs):
        hapus_id    = kwargs['hapus_id']
        Grup.objects.filter(id=hapus_id).delete()
        return super().get_redirect_url()

project/grup/templates/grup/index.html
{% extends 'base.html' %}
{% load static %}


{% block styles_custom %}
<!-- Custom styles for this page -->
<link href="{% static "vendor/datatables/dataTables.bootstrap4.min.css" %}" rel="stylesheet">
{% endblock styles_custom %}


{% block heading %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{Judul}}</h1>
    <a href="{% url "grup:tambah" %}" class="btn btn-success btn-icon-split">
        <span class="icon text-white-50">
            <i class="fas fa-plus"></i>
        </span>
        <span class="text">Tambah Grup</span>
    </a>
</div>
{% endblock heading %}


{% block data_table %}
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">{{Judul_Tabel}}</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama Grup</th>
                    <th>Menu</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>No</th>
                    <th>Nama Grup</th>
                    <th>Menu</th>
                </tr>
            </tfoot>
            <tbody>
                {% for grup in Grups %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{grup.name}}</td>
                    <td>
                        <a class="btn btn-warning" href="{% url 'grup:ubah' grup.id %}"><i class="fas fa-edit"></i></a>
                        <a class="btn btn-danger" href="{% url 'grup:hapus' grup.id %}"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>
{% endblock data_table %}


{% block scripts_custom %}
<!-- Page level plugins -->
<script src="{% static "vendor/datatables/jquery.dataTables.min.js" %}"></script>
<script src="{% static "vendor/datatables/dataTables.bootstrap4.min.js" %}"></script>

<!-- Page level custom scripts -->
<script src="{% static "js/demo/datatables-demo.js" %}"></script>
{% endblock scripts_custom %}

project/grup/templates/grup/tambah.html
{% extends 'base.html' %}
{% load static %}


{% block styles_custom %}
<!-- Custom styles for this page -->
<link href="{% static "vendor/datatables/dataTables.bootstrap4.min.css" %}" rel="stylesheet">
{% endblock styles_custom %}


{% block heading %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{Judul}}</h1>
</div>
{% endblock heading %}


{% block tambah %}
<div class="row">
    <div class="col-lg-12">
        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{Subjudul}}</h6>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label for="{{desa_form.name.id_for_label}}" class="col-sm-2 col-form-label">
                            {{grup_form.name.label}}
                        </label>
                        <div class="col-sm-10">
                            {{grup_form.name}}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success float-right">Buat</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock tambah %}


{% block scripts_custom %}
<!-- Page level plugins -->
<script src="{% static "vendor/datatables/jquery.dataTables.min.js" %}"></script>
<script src="{% static "vendor/datatables/dataTables.bootstrap4.min.js" %}"></script>

<!-- Page level custom scripts -->
<script src="{% static "js/demo/datatables-demo.js" %}"></script>
{% endblock scripts_custom %}