project/desa/urls.py
from django.urls import path, re_path

from .views import DesaListView, DesaFormView, DesaDeleteView

urlpatterns = [
    path('', DesaListView.as_view(), name="index"),
    path('tambah', DesaFormView.as_view(), name="tambah"),
    re_path(r'^ubah/(?P<ubah_id>[0-9]+)/$', DesaFormView.as_view(mode='ubah'), name="ubah"),
    re_path(r'^hapus/(?P<hapus_id>[0-9]+)/$', DesaDeleteView.as_view(), name="hapus"),
]

project/kontak/urls.py
from django.urls import path, re_path

from .views import KontakListView, KontakCariListView, KontakFormView, KontakDeleteView

urlpatterns = [
    path('', KontakListView.as_view(), name="index"),
    path('cari/', KontakCariListView.as_view(), name="cari"),
    path('tambah/', KontakFormView.as_view(), name="tambah"),
    re_path(r'^ubah/(?P<ubah_id>[0-9]+)/$', KontakFormView.as_view(mode='ubah'), name="ubah"),
    re_path(r'^hapus/(?P<hapus_id>[0-9]+)/$', KontakDeleteView.as_view(), name="hapus"),
]

project/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import DashboardListView

urlpatterns = [
    path('', DashboardListView.as_view(), name="index"),
    path('desa/', include(('desa.urls', 'desa'), namespace="desa")),
    path('grup/', include(('grup.urls', 'grup'), namespace="grup")),
    path('kontak/', include(('kontak.urls', 'kontak'), namespace="kontak")),
    path('pesan/', include(('pesan.urls', 'pesan'), namespace="pesan")),
    path('admin/', admin.site.urls),
]

project/kontak/models.py
from django.db import models
from django.db.models import Q

from grup.models import Grup
from desa.models import Desa


class KontakQuerySet(models.QuerySet):
    def search(self, query=None):
        qs  = self
        if (query is not None):
            or_lookup   = (Q(name__icontains=query) | Q(contact__icontains=query))
            qs          = qs.filter(or_lookup).distinct()
        return qs


class KontakManager(models.Manager):
    def get_queryset(self):
        return KontakQuerySet(self.model, using=self._db)
    
    def search(self, query=None):
        return self.get_queryset().search(query=query)


# Create your models here.
class Contacts(models.Model):
    norm        = models.CharField(max_length=50, null=True, blank=True)
    name        = models.CharField(max_length=50)
    contact     = models.CharField(max_length=50)
    group       = models.ForeignKey(Grup, on_delete=models.SET_NULL, null=True)
    desa        = models.ForeignKey(Desa, on_delete=models.SET_NULL, null=True, blank=True)
    is_active   = models.IntegerField(default=1)
    is_tester   = models.IntegerField(default=0)

    def __str__(self):
        return "{}. {} - {}".format(self.id, self.name, self.contact)
    
    class Meta:
        db_table    = "contacts"
    
    objects     = KontakManager()

project/kontak/forms.py
from django import forms

from .models import Contacts


class KontakForm(forms.ModelForm):
    class Meta:
        model   = Contacts
        fields  = ['norm', 'name', 'contact', 'group', 'desa']
        labels  = {
            'norm': 'No RM',
            'name': 'Nama',
            'contact': 'No HP',
            'group': 'Grup',
        }
        widgets = {
            'norm': forms.TextInput(
                attrs   = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan No RM',
                }
            ),
            'name': forms.TextInput(
                attrs   = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan nama kontak',
                }
            ),
            'contact': forms.TextInput(
                attrs   = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan No HP',
                }
            ),
            'group': forms.Select(
                attrs   = {
                    'class': 'form-control',
                    'id': 'id_group',
                }
            ),
            'desa': forms.Select(
                attrs   = {
                    'class': 'form-control',
                    'id': 'id_desa',
                }
            ),
        }

project/kontak/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView, View, RedirectView
from django.views.generic import ListView

# Create your views here.
from .models import Contacts
from .forms import KontakForm


class KontakListView(ListView):
    model       = Contacts
    ordering    = ['-id']
    paginate_by = 5
    kontaks     = Contacts.objects.all()
    extra_context   = {
        'Judul'         : 'Lihat Kontak',
        'Judul_Tabel'   : 'Tabel Kontak',
        'Total_Kontak'  : kontaks.count(),
    }
    def get_context_data(self, *args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs  = self.kwargs
        return super().get_context_data(*args, **kwargs)


class KontakFormView(View):
    template_name   = 'kontak/tambah.html'
    form    = KontakForm()
    mode    = None
    context = {}

    def get(self, *args, **kwargs):
        if self.mode == 'ubah':
            kontak_ubah = Contacts.objects.get(id=kwargs['ubah_id'])
            data        = kontak_ubah.__dict__
            self.form   = KontakForm(initial=data, instance=kontak_ubah)
        self.context    = {
            'Judul'         : 'Tambah Kontak',
            'Subjudul'      : 'Masukkan Kontak Baru',
            'kontak_form'   : self.form
        }
        return render(self.request, self.template_name, self.context)
    
    def post(self, *args, **kwargs):
        if kwargs.__contains__('ubah_id'):
            kontak_ubah = Contacts.objects.get(id=kwargs['ubah_id'])
            self.form   = KontakForm(self.request.POST, instance=kontak_ubah)
        else:
            self.form   = KontakForm(self.request.POST)
        if self.form.is_valid():
            self.form.save()
        return redirect('kontak:index')


class KontakDeleteView(RedirectView):
    pattern_name    = 'kontak:index'
    permanent       = False
    query_string    = False

    def get_redirect_url(self, *args, **kwargs):
        hapus_id    = kwargs['hapus_id']
        Contacts.objects.filter(id=hapus_id).delete()
        return super().get_redirect_url()

class KontakCariListView(ListView):
    model           = Contacts
    template_name   = 'kontak/cari_list.html'
    ordering        = ['id']
    count           = 0
    paginate_by     = 10
    extra_context   = {
        'Judul'         : 'Cari Kontak',
        'Judul_Tabel'   : 'Tabel Hasil Pencarian',
    }
    def get_context_data(self, *args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs              = self.kwargs
        context             = super().get_context_data(*args, **kwargs)
        context['count']    = self.count or 0
        context['query']    = self.request.GET.get('q')
        return context
    
    def get_queryset(self):
        request = self.request
        query   = request.GET.get('q', None)
        if query is not None:
            kontak_results  = Contacts.objects.search(query)
            qs              = sorted(kontak_results, key=lambda instance: instance.pk, reverse=True)
            self.count      = len(qs)
            return qs
        return Contacts.objects.none()

project/kontak/templates/kontak/cari_list.html
{% extends 'base.html' %}
{% load static %}

{% block heading %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{Judul}}</h1>
</div>
{% endblock heading %}

{% block cari %}
<div class="container">
    <form method="GET" action=".">
        <div class="form-group container">
            <label for="cariKontak" class="font-weight-bold">Saya ingin mencari ...</label>
            <input type="text" name="q" class="form-control" id="cariKontak" aria-describedby="helpKontak" placeholder="...">
            <small id="helpKontak" class="form-text text-muted">Masukkan nama/nomor kontak</small>
          </div>
    </form>
</div>
{% endblock cari %}

{% block data_table %}
    {% if query is not None %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{Judul_Tabel}}</h6>
        </div>
        <div class="card-body">
            <h6 class="font-weight-bold text-right">Total: {{count}}</h6>
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>No RM</th>
                            <th>Nama</th>
                            <th>Nomor HP</th>
                            <th>Grup</th>
                            <th>Desa</th>
                            <th>Menu</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>No</th>
                            <th>No RM</th>
                            <th>Nama</th>
                            <th>Nomor HP</th>
                            <th>Grup</th>
                            <th>Desa</th>
                            <th>Menu</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for kontak in object_list %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            {% if kontak.norm is None %}
                                <td>-</td>
                            {% else %}
                                <td>{{kontak.norm}}</td>
                            {% endif %}
                            <td>{{kontak.name}}</td>
                            <td>{{kontak.contact}}</td>
                            <td>{{kontak.group}}</td>
                            {% if kontak.desa is None %}
                                <td>-</td>
                            {% else %}
                                <td>{{kontak.desa}}</td>
                            {% endif %}
                            <td>
                                <a class="btn btn-warning" href="{% url 'kontak:ubah' kontak.id %}"><i class="fas fa-edit"></i></a>
                                <a class="btn btn-danger" href="{% url 'kontak:hapus' kontak.id %}"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="7" style="text-align: center;">Data kontak "{{query}}" tidak ditemukan</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% if is_paginated %}
                <ul class="pagination justify-content-end">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?q={{ query }}&page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span>Previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span>Previous</span>
                            </a>
                        </li>
                    {% endif %}
                    {% if page_obj.number|add:'-4' > 1 %}
                        <li class="page-item">
                            <a class="page-link" href="?q={{ query }}&page={{ page_obj.number|add:'-5' }}">&hellip;</a>
                        </li>
                    {% endif %}

                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="active page-item">
                                <a href="#" class="page-link">
                                    <span>{{ i }} <span class="sr-only">(current)</span></span>
                                </a>
                            </li>
                        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                            <li class="page-item"><a class="page-link" href="?q={{ query }}&page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                        <li class="page-item">
                            <a class="page-link" href="?q={{ query }}&page={{ page_obj.number|add:'5' }}">&hellip;</a>
                        </li>
                    {% endif %}
                    
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?q={{ query }}&page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span>Next</span>
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" aria-label="Next">
                                <span>Next</span>
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
    {% endif %}
{% endblock data_table %}

project/kontak/templates/kontak/contacts_list.html
{% extends 'base.html' %}
{% load static %}

{% block heading %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{Judul}}</h1>
    <div class="justify-content-end">
        <a href="{% url "kontak:tambah" %}" class="btn btn-success btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-plus"></i>
            </span>
            <span class="text">Tambah Kontak</span>
        </a>
        <a href="{% url "kontak:cari" %}" class="btn btn-warning btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-search"></i>
            </span>
            <span class="text">Cari Kontak</span>
        </a>
    </div>
</div>
{% endblock heading %}

{% block data_table %}
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">{{Judul_Tabel}}</h6>
    </div>
    <div class="card-body">
        <h6 class="font-weight-bold text-right">Total: {{ Total_Kontak }}</h6>
        <div class="table-responsive">
            <table class="table table-bordered" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>No RM</th>
                        <th>Nama</th>
                        <th>Nomor HP</th>
                        <th>Grup</th>
                        <th>Desa</th>
                        <th>Menu</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>No</th>
                        <th>No RM</th>
                        <th>Nama</th>
                        <th>Nomor HP</th>
                        <th>Grup</th>
                        <th>Desa</th>
                        <th>Menu</th>
                    </tr>
                </tfoot>
                <tbody>
                    {% for kontak in object_list %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        {% if kontak.norm is None %}
                            <td>-</td>
                        {% else %}
                            <td>{{kontak.norm}}</td>
                        {% endif %}
                        <td>{{kontak.name}}</td>
                        <td>{{kontak.contact}}</td>
                        <td>{{kontak.group}}</td>
                        {% if kontak.desa is None %}
                            <td>-</td>
                        {% else %}
                            <td>{{kontak.desa}}</td>
                        {% endif %}
                        <td>
                            <a class="btn btn-warning" href="{% url 'kontak:ubah' kontak.id %}"><i class="fas fa-edit"></i></a>
                            <a class="btn btn-danger" href="{% url 'kontak:hapus' kontak.id %}"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if is_paginated %}
            <ul class="pagination justify-content-end">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span>Previous</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span>Previous</span>
                        </a>
                    </li>
                {% endif %}
                {% if page_obj.number|add:'-4' > 1 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a>
                    </li>
                {% endif %}

                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active page-item">
                            <a href="#" class="page-link">
                                <span>{{ i }} <span class="sr-only">(current)</span></span>
                            </a>
                        </li>
                    {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a>
                    </li>
                {% endif %}
                
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span>Next</span>
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Next">
                            <span>Next</span>
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock data_table %}

project/kontak/templates/kontak/tambah.html
{% extends 'base.html' %}
{% load static %}

{% block heading %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{Judul}}</h1>
</div>
{% endblock heading %}


{% block tambah %}
<div class="row">
    <div class="col-lg-12">
        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{Subjudul}}</h6>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in kontak_form %}
                        <div class="form-group row">
                            <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{field.label}}</label>
                            <div class="col-sm-10">
                                {{field}}
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-success float-right">Buat</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock tambah %}